# Generated by Django 5.1.2 on 2024-11-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
