# Generated by Django 5.1.2 on 2024-11-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0002_alter_player_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='rounds',
            field=models.ManyToManyField(blank=True, to='torneos.round'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_players',
            field=models.ManyToManyField(blank=True, to='torneos.topplayer'),
        ),
    ]
