# Generated by Django 5.1.2 on 2024-11-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0003_alter_tournament_rounds_alter_tournament_top_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='top_players',
        ),
        migrations.AddField(
            model_name='tournament',
            name='top_players_4',
            field=models.ManyToManyField(blank=True, related_name='top_4', to='torneos.topplayer'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='top_players_8',
            field=models.ManyToManyField(blank=True, related_name='top_8', to='torneos.topplayer'),
        ),
        migrations.AlterField(
            model_name='round',
            name='emparents',
            field=models.ManyToManyField(blank=True, to='torneos.emparents'),
        ),
    ]
