# Generated by Django 5.1.2 on 2024-11-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0004_remove_tournament_top_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(blank=True, to='torneos.tournamentplayer'),
        ),
    ]
