# Generated by Django 5.1.2 on 2024-11-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0005_alter_tournament_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
