# Generated by Django 5.1.2 on 2024-11-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0007_alter_tournamentplayer_ogw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='top_players_4',
            field=models.ManyToManyField(blank=True, related_name='top_4', to='torneos.tournamentplayer'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_players_8',
            field=models.ManyToManyField(blank=True, related_name='top_8', to='torneos.tournamentplayer'),
        ),
    ]
