# Generated by Django 5.1.2 on 2024-11-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0011_alter_tournament_top_players_4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emparents',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
