# Generated by Django 5.1.2 on 2024-11-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0013_tournament_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='emparents',
            name='final',
            field=models.CharField(default='round', max_length=150),
        ),
    ]
