# Generated by Django 5.1.2 on 2024-12-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torneos", "0015_rename_player_topplayer_tournament_player_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="address",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="place",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
