# Generated by Django 5.1.2 on 2024-12-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0016_tournament_address_tournament_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='decks'),
        ),
    ]
